package com.uclgroupgh.form.entities;
// Generated Feb 25, 2019 8:12:08 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord;

import java.util.Date;

/**
 * AggregationCenters generated by hbm2java
 */
public class AggregationCenters extends SugarRecord {


    public String macaddress;
    public String imei;
    public String uniqueuid;
    public String agentname;
    public Date entrydate;
    public String collectorid;
    public String collectorName;
    public String storageFacilityName;
    public String location;
    public String newConstructionType;
    public String refurbishedType;
    public String warehouseType;
    public String silosType;
    public String picsbagsType;
    public String storesType;
    public String volume;
    public String crop;
    public String quantityStored;
    public String handlingCost;
    public String currency;
    public String servedFarmers;
    public String quantitySold;
    public String averagePrice;
    public int serverid;

    public AggregationCenters() {
    }

    public AggregationCenters(String macaddress, String imei, String uniqueuid, String agentname, Date entrydate, String collectorid, String collectorName, String storageFacilityName, String location, String newConstructionType, String refurbishedType, String warehouseType, String silosType, String picsbagsType, String storesType, String volume, String crop, String quantityStored, String handlingCost, String currency, String servedFarmers, String quantitySold, String averagePrice, int serverid) {
        this.macaddress = macaddress;
        this.imei = imei;
        this.uniqueuid = uniqueuid;
        this.agentname = agentname;
        this.entrydate = entrydate;
        this.collectorid = collectorid;
        this.collectorName = collectorName;
        this.storageFacilityName = storageFacilityName;
        this.location = location;
        this.newConstructionType = newConstructionType;
        this.refurbishedType = refurbishedType;
        this.warehouseType = warehouseType;
        this.silosType = silosType;
        this.picsbagsType = picsbagsType;
        this.storesType = storesType;
        this.volume = volume;
        this.crop = crop;
        this.quantityStored = quantityStored;
        this.handlingCost = handlingCost;
        this.currency = currency;
        this.servedFarmers = servedFarmers;
        this.quantitySold = quantitySold;
        this.averagePrice = averagePrice;
        this.serverid = serverid;
    }

    public int getServerid() {
        return serverid;
    }

    public void setServerid(int serverid) {
        this.serverid = serverid;
    }

    public String getMacaddress() {
        return this.macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getImei() {
        return this.imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getUniqueuid() {
        return this.uniqueuid;
    }

    public void setUniqueuid(String uniqueuid) {
        this.uniqueuid = uniqueuid;
    }

    public String getAgentname() {
        return this.agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public Date getEntrydate() {
        return this.entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }

    public String getCollectorid() {
        return this.collectorid;
    }

    public void setCollectorid(String collectorid) {
        this.collectorid = collectorid;
    }

    public String getCollectorName() {
        return this.collectorName;
    }

    public void setCollectorName(String collectorName) {
        this.collectorName = collectorName;
    }

    public String getStorageFacilityName() {
        return this.storageFacilityName;
    }

    public void setStorageFacilityName(String storageFacilityName) {
        this.storageFacilityName = storageFacilityName;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getNewConstructionType() {
        return this.newConstructionType;
    }

    public void setNewConstructionType(String newConstructionType) {
        this.newConstructionType = newConstructionType;
    }

    public String getRefurbishedType() {
        return this.refurbishedType;
    }

    public void setRefurbishedType(String refurbishedType) {
        this.refurbishedType = refurbishedType;
    }

    public String getWarehouseType() {
        return this.warehouseType;
    }

    public void setWarehouseType(String warehouseType) {
        this.warehouseType = warehouseType;
    }

    public String getSilosType() {
        return this.silosType;
    }

    public void setSilosType(String silosType) {
        this.silosType = silosType;
    }

    public String getPicsbagsType() {
        return this.picsbagsType;
    }

    public void setPicsbagsType(String picsbagsType) {
        this.picsbagsType = picsbagsType;
    }

    public String getStoresType() {
        return this.storesType;
    }

    public void setStoresType(String storesType) {
        this.storesType = storesType;
    }

    public String getVolume() {
        return this.volume;
    }

    public void setVolume(String volume) {
        this.volume = volume;
    }

    public String getCrop() {
        return this.crop;
    }

    public void setCrop(String crop) {
        this.crop = crop;
    }

    public String getQuantityStored() {
        return this.quantityStored;
    }

    public void setQuantityStored(String quantityStored) {
        this.quantityStored = quantityStored;
    }

    public String getHandlingCost() {
        return this.handlingCost;
    }

    public void setHandlingCost(String handlingCost) {
        this.handlingCost = handlingCost;
    }

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getServedFarmers() {
        return this.servedFarmers;
    }

    public void setServedFarmers(String servedFarmers) {
        this.servedFarmers = servedFarmers;
    }

    public String getQuantitySold() {
        return this.quantitySold;
    }

    public void setQuantitySold(String quantitySold) {
        this.quantitySold = quantitySold;
    }

    public String getAveragePrice() {
        return this.averagePrice;
    }

    public void setAveragePrice(String averagePrice) {
        this.averagePrice = averagePrice;
    }
}


