package com.uclgroupgh.form.entities

// Generated Feb 25, 2019 8:12:08 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord

import java.util.Date

/**
 * CollectorInfo generated by hbm2java
 */
class CollectorInfo() : SugarRecord() {

    var collectorname: String? = null
    var country: String? = null
    var region: String? = null
    var project: String? = null
    var collectorid: String? = null
    var grantee: String? = null
    var year: String? = null
    var district: String? = null
    var quarter: String? = null
    var entrydate: Date? = null
    var macaddress: String? = null
    var signature: ByteArray? = null
    var imei: String? = null
    var agentname: String? = null
    var uniqueuid: String? = null
    var eventType: String? = null
    var serverid: Int = 0

}


