package com.uclgroupgh.form.entities

// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord

import java.util.Date

/**
 * Farmers generated by hbm2java
 */
class Farmers : SugarRecord {
    var age: Int? = null
    var farmerid: String? = null
    var surname: String? = null
    var othername: String? = null
    var placeofbirth: String? = null
    var dateofbirth: Date? = null
    var gender: String? = null
    var hometown: String? = null
    var address: String? = null
    var district: String? = null
    var region: String? = null
    var country: String? = null
    var idcardtype: String? = null
    var idcardno: String? = null
    var levelofeducation: String? = null
    var religion: String? = null
    var maritalstatus: String? = null
    var nextofkin: String? = null
    var relation: String? = null
    var qfarmergroup: String? = null
    var farmergroup: String? = null
    var qcooperative: String? = null
    var cooperative: String? = null
    var qincomesource: String? = null
    var incomesource: String? = null
    var qspecialty: String? = null
    var specialty: String? = null
    var certification: String? = null
    var funding: String? = null
    var imagelink: String? = null
    var community: String? = null
    var tel: String? = null
    var email: String? = null
    var uniqueuid: String? = null
    var postbox: String? = null
    var synstatus: String? = null
    var datecreated: Date? = null
    var macaddress: String? = null
    var imei: String? = null
    var agentname: String? = null
    var agentid: String? = null
    var serverid: Int? = 0
    var isSelected = false


    constructor()

    constructor(
        farmerid: String,
        surname: String,
        othername: String,
        placeofbirth: String,
        dateofbirth: Date,
        age: Int?,
        gender: String,
        hometown: String,
        address: String,
        district: String,
        region: String,
        country: String,
        idcardtype: String,
        idcardno: String,
        levelofeducation: String,
        religion: String,
        maritalstatus: String,
        nextofkin: String,
        relation: String,
        qfarmergroup: String,
        farmergroup: String,
        qcooperative: String,
        cooperative: String,
        qincomesource: String,
        incomesource: String,
        qspecialty: String,
        specialty: String,
        certification: String,
        funding: String,
        imagelink: String,
        community: String,
        tel: String,
        email: String,
        uniqueuid: String,
        postbox: String,
        synstatus: String,
        datecreated: Date,
        serverid: Int,
        macaddress: String,
        imei: String,
        agentname: String,
        agentid: String
    ) {
        this.farmerid = farmerid
        this.surname = surname
        this.othername = othername
        this.placeofbirth = placeofbirth
        this.dateofbirth = dateofbirth
        this.age = age
        this.gender = gender
        this.hometown = hometown
        this.address = address
        this.district = district
        this.region = region
        this.country = country
        this.idcardtype = idcardtype
        this.idcardno = idcardno
        this.levelofeducation = levelofeducation
        this.religion = religion
        this.maritalstatus = maritalstatus
        this.nextofkin = nextofkin
        this.relation = relation
        this.qfarmergroup = qfarmergroup
        this.farmergroup = farmergroup
        this.qcooperative = qcooperative
        this.cooperative = cooperative
        this.qincomesource = qincomesource
        this.incomesource = incomesource
        this.qspecialty = qspecialty
        this.specialty = specialty
        this.certification = certification
        this.funding = funding
        this.imagelink = imagelink
        this.community = community
        this.tel = tel
        this.email = email
        this.uniqueuid = uniqueuid
        this.postbox = postbox
        this.synstatus = synstatus
        this.datecreated = datecreated
        this.serverid = serverid
        this.macaddress = macaddress
        this.imei = imei
        this.agentname = agentname
        this.agentid = agentid
    }


    constructor(
        farmerid: String,
        surname: String,
        placeofbirth: String,
        dateofbirth: Date,
        gender: String,
        district: String,
        region: String,
        country: String,
        idcardtype: String,
        idcardno: String,
        levelofeducation: String,
        maritalstatus: String,
        qfarmergroup: String,
        qcooperative: String,
        cooperative: String,
        qincomesource: String,
        qspecialty: String,
        certification: String,
        funding: String,
        imagelink: String,
        community: String
    ) {
        this.farmerid = farmerid
        this.surname = surname
        this.placeofbirth = placeofbirth
        this.dateofbirth = dateofbirth
        this.gender = gender
        this.district = district
        this.region = region
        this.country = country
        this.idcardtype = idcardtype
        this.idcardno = idcardno
        this.levelofeducation = levelofeducation
        this.maritalstatus = maritalstatus
        this.qfarmergroup = qfarmergroup
        this.qcooperative = qcooperative
        this.cooperative = cooperative
        this.qincomesource = qincomesource
        this.qspecialty = qspecialty
        this.certification = certification
        this.funding = funding
        this.imagelink = imagelink
        this.community = community
    }

    constructor(
        farmerid: String,
        surname: String,
        othername: String,
        placeofbirth: String,
        dateofbirth: Date,
        gender: String,
        hometown: String,
        address: String,
        district: String,
        region: String,
        country: String,
        idcardtype: String,
        idcardno: String,
        levelofeducation: String,
        religion: String,
        maritalstatus: String,
        nextofkin: String,
        relation: String,
        qfarmergroup: String,
        farmergroup: String,
        qcooperative: String,
        cooperative: String,
        qincomesource: String,
        incomesource: String,
        qspecialty: String,
        specialty: String,
        certification: String,
        funding: String,
        imagelink: String,
        community: String,
        tel: String
    ) {
        this.farmerid = farmerid
        this.surname = surname
        this.othername = othername
        this.placeofbirth = placeofbirth
        this.dateofbirth = dateofbirth
        this.gender = gender
        this.hometown = hometown
        this.address = address
        this.district = district
        this.region = region
        this.country = country
        this.idcardtype = idcardtype
        this.idcardno = idcardno
        this.levelofeducation = levelofeducation
        this.religion = religion
        this.maritalstatus = maritalstatus
        this.nextofkin = nextofkin
        this.relation = relation
        this.qfarmergroup = qfarmergroup
        this.farmergroup = farmergroup
        this.qcooperative = qcooperative
        this.cooperative = cooperative
        this.qincomesource = qincomesource
        this.incomesource = incomesource
        this.qspecialty = qspecialty
        this.specialty = specialty
        this.certification = certification
        this.funding = funding
        this.imagelink = imagelink
        this.community = community
        this.tel = tel
    }


}


