package com.uclgroupgh.form.entities;
// Generated Feb 25, 2019 8:12:08 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord;

import java.util.Date;

/**
 * FertilizerBlending generated by hbm2java
 */
public class FertilizerBlending extends SugarRecord {

    public String soillabname;
    public String soillabtest;
    public Integer numberofblends;
    public String typeofagrasupport;
    public String crops;
    public String fertilizercompanies;
    public Integer quantityproduced;
    public Integer quantitysold;
    public String collectorid;
    public String collectorname;
    public String imei;
    public String macaddress;
    public String uniqueuid;
    public String agentname;
    public Date entrydate;
    public int serverid;


    public FertilizerBlending() {
    }

    public FertilizerBlending(String soillabname, String soillabtest, Integer numberofblends, String typeofagrasupport, String crops, String fertilizercompanies, Integer quantityproduced, Integer quantitysold, String collectorid, String collectorname, String imei, String macaddress, String uniqueuid, String agentname, Date entrydate) {
        this.soillabname = soillabname;
        this.soillabtest = soillabtest;
        this.numberofblends = numberofblends;
        this.typeofagrasupport = typeofagrasupport;
        this.crops = crops;
        this.fertilizercompanies = fertilizercompanies;
        this.quantityproduced = quantityproduced;
        this.quantitysold = quantitysold;
        this.collectorid = collectorid;
        this.collectorname = collectorname;
        this.imei = imei;
        this.macaddress = macaddress;
        this.uniqueuid = uniqueuid;
        this.agentname = agentname;
        this.entrydate = entrydate;
    }

    public int getServerid() {
        return serverid;
    }

    public void setServerid(int serverid) {
        this.serverid = serverid;
    }

    public String getSoillabname() {
        return this.soillabname;
    }

    public void setSoillabname(String soillabname) {
        this.soillabname = soillabname;
    }

    public String getSoillabtest() {
        return this.soillabtest;
    }

    public void setSoillabtest(String soillabtest) {
        this.soillabtest = soillabtest;
    }

    public Integer getNumberofblends() {
        return this.numberofblends;
    }

    public void setNumberofblends(Integer numberofblends) {
        this.numberofblends = numberofblends;
    }

    public String getTypeofagrasupport() {
        return this.typeofagrasupport;
    }

    public void setTypeofagrasupport(String typeofagrasupport) {
        this.typeofagrasupport = typeofagrasupport;
    }

    public String getCrops() {
        return this.crops;
    }

    public void setCrops(String crops) {
        this.crops = crops;
    }

    public String getFertilizercompanies() {
        return this.fertilizercompanies;
    }

    public void setFertilizercompanies(String fertilizercompanies) {
        this.fertilizercompanies = fertilizercompanies;
    }

    public Integer getQuantityproduced() {
        return this.quantityproduced;
    }

    public void setQuantityproduced(Integer quantityproduced) {
        this.quantityproduced = quantityproduced;
    }

    public Integer getQuantitysold() {
        return this.quantitysold;
    }

    public void setQuantitysold(Integer quantitysold) {
        this.quantitysold = quantitysold;
    }

    public String getCollectorid() {
        return this.collectorid;
    }

    public void setCollectorid(String collectorid) {
        this.collectorid = collectorid;
    }

    public String getCollectorname() {
        return this.collectorname;
    }

    public void setCollectorname(String collectorname) {
        this.collectorname = collectorname;
    }

    public String getImei() {
        return this.imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getMacaddress() {
        return this.macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getUniqueuid() {
        return this.uniqueuid;
    }

    public void setUniqueuid(String uniqueuid) {
        this.uniqueuid = uniqueuid;
    }

    public String getAgentname() {
        return this.agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public Date getEntrydate() {
        return this.entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }


}


