package com.uclgroupgh.form.entities;
// Generated Feb 25, 2019 8:12:08 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord;

import java.util.Date;

/**
 * ParticipationInAgraEvent generated by hbm2java
 */
public class ParticipationInAgraEvent extends SugarRecord {

    public String extentionevent;
    public Integer nocompleted;
    public String farmergender;
    public String chainactorgender;
    public String collectorid;
    public String collectorname;
    public String agentname;
    public String imei;
    public String macaddress;
    public String uniqueuid;
    public Date entrydate;
    public int serverid;

    public ParticipationInAgraEvent() {
    }

    public ParticipationInAgraEvent(String extentionevent, Integer nocompleted, String farmergender, String chainactorgender, String collectorid, String collectorname, String agentname, String imei, String macaddress, String uniqueuid, Date entrydate) {
        this.extentionevent = extentionevent;
        this.nocompleted = nocompleted;
        this.farmergender = farmergender;
        this.chainactorgender = chainactorgender;
        this.collectorid = collectorid;
        this.collectorname = collectorname;
        this.agentname = agentname;
        this.imei = imei;
        this.macaddress = macaddress;
        this.uniqueuid = uniqueuid;
        this.entrydate = entrydate;
    }

    public int getServerid() {
        return serverid;
    }

    public void setServerid(int serverid) {
        this.serverid = serverid;
    }

    public String getExtentionevent() {
        return this.extentionevent;
    }

    public void setExtentionevent(String extentionevent) {
        this.extentionevent = extentionevent;
    }

    public Integer getNocompleted() {
        return this.nocompleted;
    }

    public void setNocompleted(Integer nocompleted) {
        this.nocompleted = nocompleted;
    }

    public String getFarmergender() {
        return this.farmergender;
    }

    public void setFarmergender(String farmergender) {
        this.farmergender = farmergender;
    }

    public String getChainactorgender() {
        return this.chainactorgender;
    }

    public void setChainactorgender(String chainactorgender) {
        this.chainactorgender = chainactorgender;
    }

    public String getCollectorid() {
        return this.collectorid;
    }

    public void setCollectorid(String collectorid) {
        this.collectorid = collectorid;
    }

    public String getCollectorname() {
        return this.collectorname;
    }

    public void setCollectorname(String collectorname) {
        this.collectorname = collectorname;
    }

    public String getAgentname() {
        return this.agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public String getImei() {
        return this.imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getMacaddress() {
        return this.macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getUniqueuid() {
        return this.uniqueuid;
    }

    public void setUniqueuid(String uniqueuid) {
        this.uniqueuid = uniqueuid;
    }

    public Date getEntrydate() {
        return this.entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }


}


