package com.uclgroupgh.form.entities;
// Generated Feb 25, 2019 8:12:08 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord;

import java.math.BigDecimal;
import java.util.Date;

/**
 * SeedProduction generated by hbm2java
 */
public class SeedProduction extends SugarRecord {

    public String item;
    public String variety;
    public String firsttimeinproduction;
    public String plotsize;
    public Integer quantityproduced;
    public Integer quantitycertified;
    public Integer quantitysold;
    public BigDecimal unitprice;
    public String currency;
    public Date datecreated;
    public String macaddress;
    public String imei;
    public String agentname;
    public String uniqueuid;
    public String agentid;
    public String collectorid;
    public String collectorname;
    public int serverid;

    public SeedProduction() {
    }

    public SeedProduction(String item, String variety, String firsttimeinproduction, String plotsize, Integer quantityproduced, Integer quantitycertified, Integer quantitysold, BigDecimal unitprice, String currency, Date datecreated, String macaddress, String imei, String agentname, String uniqueuid, String agentid, String collectorid, String collectorname) {
        this.item = item;
        this.variety = variety;
        this.firsttimeinproduction = firsttimeinproduction;
        this.plotsize = plotsize;
        this.quantityproduced = quantityproduced;
        this.quantitycertified = quantitycertified;
        this.quantitysold = quantitysold;
        this.unitprice = unitprice;
        this.currency = currency;
        this.datecreated = datecreated;
        this.macaddress = macaddress;
        this.imei = imei;
        this.agentname = agentname;
        this.uniqueuid = uniqueuid;
        this.agentid = agentid;
        this.collectorid = collectorid;
        this.collectorname = collectorname;
    }

    public int getServerid() {
        return serverid;
    }

    public void setServerid(int serverid) {
        this.serverid = serverid;
    }

    public String getItem() {
        return this.item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public String getVariety() {
        return this.variety;
    }

    public void setVariety(String variety) {
        this.variety = variety;
    }

    public String getFirsttimeinproduction() {
        return this.firsttimeinproduction;
    }

    public void setFirsttimeinproduction(String firsttimeinproduction) {
        this.firsttimeinproduction = firsttimeinproduction;
    }

    public String getPlotsize() {
        return this.plotsize;
    }

    public void setPlotsize(String plotsize) {
        this.plotsize = plotsize;
    }

    public Integer getQuantityproduced() {
        return this.quantityproduced;
    }

    public void setQuantityproduced(Integer quantityproduced) {
        this.quantityproduced = quantityproduced;
    }

    public Integer getQuantitycertified() {
        return this.quantitycertified;
    }

    public void setQuantitycertified(Integer quantitycertified) {
        this.quantitycertified = quantitycertified;
    }

    public Integer getQuantitysold() {
        return this.quantitysold;
    }

    public void setQuantitysold(Integer quantitysold) {
        this.quantitysold = quantitysold;
    }

    public BigDecimal getUnitprice() {
        return this.unitprice;
    }

    public void setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
    }

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Date getDatecreated() {
        return this.datecreated;
    }

    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }

    public String getMacaddress() {
        return this.macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getImei() {
        return this.imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getAgentname() {
        return this.agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public String getUniqueuid() {
        return this.uniqueuid;
    }

    public void setUniqueuid(String uniqueuid) {
        this.uniqueuid = uniqueuid;
    }

    public String getAgentid() {
        return this.agentid;
    }

    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    public String getCollectorid() {
        return this.collectorid;
    }

    public void setCollectorid(String collectorid) {
        this.collectorid = collectorid;
    }

    public String getCollectorname() {
        return this.collectorname;
    }

    public void setCollectorname(String collectorname) {
        this.collectorname = collectorname;
    }


}


