package com.uclgroupgh.form.entities;
// Generated Feb 25, 2019 8:12:08 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord;

import java.util.Date;

/**
 * SupportedEnterprise generated by hbm2java
 */
public class SupportedEnterprise extends SugarRecord {

    public String collectorid;
    public String imei;
    public String macaddress;
    public String uniqueuid;
    public String collectorName;
    public String enterpriseName;
    public String contacts;
    public String agroDealerType;
    public String seedProducer;
    public String femaleOwnerStatus;
    public String youthOwnerStatus;
    public String fullTimeEmploymentGender;
    public String casualEmploymentGender;
    public String partTimeEmploymentGender;
    public String ageGroup;
    public String agentname;
    public Date entrydate;
    public int serverid;

    public SupportedEnterprise() {
    }

    public SupportedEnterprise(String collectorid, String collectorName, String imei, String macaddress, String uniqueuid, String enterpriseName, String contacts, String agroDealerType, String seedProducer, String femaleOwnerStatus, String youthOwnerStatus, String fullTimeEmploymentGender, String partTimeEmploymentGender, String casualEmploymentGender, String ageGroup, String agentname, Date entrydate) {
        this.collectorid = collectorid;
        this.collectorName = collectorName;
        this.imei = imei;
        this.macaddress = macaddress;
        this.uniqueuid = uniqueuid;
        this.enterpriseName = enterpriseName;
        this.contacts = contacts;
        this.agroDealerType = agroDealerType;
        this.seedProducer = seedProducer;
        this.femaleOwnerStatus = femaleOwnerStatus;
        this.youthOwnerStatus = youthOwnerStatus;
        this.fullTimeEmploymentGender = fullTimeEmploymentGender;
        this.partTimeEmploymentGender = partTimeEmploymentGender;
        this.casualEmploymentGender = casualEmploymentGender;
        this.ageGroup = ageGroup;
        this.agentname = agentname;
        this.entrydate = entrydate;
    }

    public int getServerid() {
        return serverid;
    }

    public void setServerid(int serverid) {
        this.serverid = serverid;
    }

    public String getCollectorName() {
        return this.collectorName;
    }

    public void setCollectorName(String collectorName) {
        this.collectorName = collectorName;
    }

    public String getImei() {
        return this.imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getMacaddress() {
        return this.macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getUniqueuid() {
        return this.uniqueuid;
    }

    public void setUniqueuid(String uniqueuid) {
        this.uniqueuid = uniqueuid;
    }

    public String getEnterpriseName() {
        return this.enterpriseName;
    }

    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName;
    }

    public String getContacts() {
        return this.contacts;
    }

    public void setContacts(String contacts) {
        this.contacts = contacts;
    }

    public String getAgroDealerType() {
        return this.agroDealerType;
    }

    public void setAgroDealerType(String agroDealerType) {
        this.agroDealerType = agroDealerType;
    }

    public String getSeedProducer() {
        return this.seedProducer;
    }

    public void setSeedProducer(String seedProducer) {
        this.seedProducer = seedProducer;
    }

    public String getFemaleOwnerStatus() {
        return this.femaleOwnerStatus;
    }

    public void setFemaleOwnerStatus(String femaleOwnerStatus) {
        this.femaleOwnerStatus = femaleOwnerStatus;
    }

    public String getYouthOwnerStatus() {
        return this.youthOwnerStatus;
    }

    public void setYouthOwnerStatus(String youthOwnerStatus) {
        this.youthOwnerStatus = youthOwnerStatus;
    }

    public String getFullTimeEmploymentGender() {
        return this.fullTimeEmploymentGender;
    }

    public void setFullTimeEmploymentGender(String fullTimeEmploymentGender) {
        this.fullTimeEmploymentGender = fullTimeEmploymentGender;
    }

    public String getPartTimeEmploymentGender() {
        return this.partTimeEmploymentGender;
    }

    public void setPartTimeEmploymentGender(String partTimeEmploymentGender) {
        this.partTimeEmploymentGender = partTimeEmploymentGender;
    }

    public String getAgeGroup() {
        return this.ageGroup;
    }

    public void setAgeGroup(String ageGroup) {
        this.ageGroup = ageGroup;
    }

    public String getAgentname() {
        return this.agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public Date getEntrydate() {
        return this.entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }

    public String getCollectorid() {
        return collectorid;
    }

    public void setCollectorid(String collectorid) {
        this.collectorid = collectorid;
    }

    public String getCasualEmploymentGender() {
        return casualEmploymentGender;
    }

    public void setCasualEmploymentGender(String casualEmploymentGender) {
        this.casualEmploymentGender = casualEmploymentGender;
    }
}


