package com.uclgroupgh.form.entities

// Generated Feb 25, 2019 8:12:08 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord

import java.util.Date

/**
 * TrainingAttendanceDialog generated by hbm2java
 */
class TrainingAttendance() : SugarRecord() {
    var traineeid: String? = null
    var title: String? = null
    var firstname: String? = null
    var lastname: String? = null
    var gender: String? = null
    var participantType: String? = null
    var function: String? = null
    var institution: String? = null
    var region: String? = null
    var districts: String? = null
    var telephone: String? = null
    var email: String? = null
    var signature: ByteArray? = null
    var agentname: String? = null
    var imei: String? = null
    var macaddress: String? = null
    var entrydate: Date? = null
    var uniqueuid: String? = null
    var collectorid: String? = null
    var collectorname: String? = null
    var serverid: Int = 0

}


