package com.uclgroupgh.form.entities;
// Generated Feb 25, 2019 8:12:08 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord;

import java.util.Date;

/**
 * TrainingInfo generated by hbm2java
 */
public class TrainingInfo extends SugarRecord {

    public String uniqueuid;
    public String macaddress;
    public String imei;
    public Date entrydate;
    public String traineeid;
    public String theme;
    public String disaggregationLevels;
    public String period;
    public String venue;
    public String trainerName;
    public String trainerContact;
    public String event;
    public String collectorid;
    public String collectorname;
    public String agentname;
    public int serverid;

    public TrainingInfo() {
    }

    public TrainingInfo(String uniqueuid, String macaddress, String imei, Date entrydate, String traineeid, String theme, String disaggregationLevels, String period, String venue, String trainerName, String trainerContact, String collectorid, String collectorname, String agentname, String event, int serverid) {
        this.uniqueuid = uniqueuid;
        this.macaddress = macaddress;
        this.imei = imei;
        this.entrydate = entrydate;
        this.traineeid = traineeid;
        this.theme = theme;
        this.disaggregationLevels = disaggregationLevels;
        this.period = period;
        this.venue = venue;
        this.trainerName = trainerName;
        this.trainerContact = trainerContact;
        this.collectorid = collectorid;
        this.collectorname = collectorname;
        this.agentname = agentname;
        this.event = event;
        this.serverid = serverid;
    }

    public int getServerid() {
        return serverid;
    }

    public void setServerid(int serverid) {
        this.serverid = serverid;
    }

    public String getEvent() {
        return event;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public String getUniqueuid() {
        return this.uniqueuid;
    }

    public void setUniqueuid(String uniqueuid) {
        this.uniqueuid = uniqueuid;
    }

    public String getMacaddress() {
        return this.macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getImei() {
        return this.imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public Date getEntrydate() {
        return entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }

    public String getAgentname() {
        return agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public String getTraineeid() {
        return this.traineeid;
    }

    public void setTraineeid(String traineeid) {
        this.traineeid = traineeid;
    }

    public String getTheme() {
        return this.theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    public String getDisaggregationLevels() {
        return this.disaggregationLevels;
    }

    public void setDisaggregationLevels(String disaggregationLevels) {
        this.disaggregationLevels = disaggregationLevels;
    }

    public String getPeriod() {
        return this.period;
    }

    public void setPeriod(String period) {
        this.period = period;
    }

    public String getVenue() {
        return this.venue;
    }

    public void setVenue(String venue) {
        this.venue = venue;
    }

    public String getTrainerName() {
        return this.trainerName;
    }

    public void setTrainerName(String trainerName) {
        this.trainerName = trainerName;
    }

    public String getTrainerContact() {
        return this.trainerContact;
    }

    public void setTrainerContact(String trainerContact) {
        this.trainerContact = trainerContact;
    }

    public String getCollectorid() {
        return this.collectorid;
    }

    public void setCollectorid(String collectorid) {
        this.collectorid = collectorid;
    }

    public String getCollectorname() {
        return this.collectorname;
    }

    public void setCollectorname(String collectorname) {
        this.collectorname = collectorname;
    }
}


