package com.uclgroupgh.form.entities

// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord

import java.util.Date

/**
 * Userbiometrics generated by hbm2java
 */
class Userbiometrics : SugarRecord {
    var farmerid: String? = null
    var picture: ByteArray? = null
    var signature: ByteArray? = null
    var height: String? = null
    var eyecolor: String? = null
    var createdDate: Date? = null
    var placeOfRegistered: String? = null
    var datecreatedserver: Date? = null
    var uniqueuid: String? = null
    var synstatus: String? = null
    var datecreated: Date? = null
    var serverid: Int? = 0
    var macaddress: String? = null
    var imei: String? = null
    var agentname: String? = null
    var agentid: String? = null

    constructor(
        farmerid: String,
        picture: ByteArray,
        signature: ByteArray,
        height: String,
        eyecolor: String,
        createdDate: Date,
        placeOfRegistered: String,
        datecreatedserver: Date,
        uniqueuid: String,
        synstatus: String,
        datecreated: Date,
        serverid: Int,
        macaddress: String,
        imei: String,
        agentname: String,
        agentid: String
    ) {
        this.farmerid = farmerid
        this.picture = picture
        this.signature = signature
        this.height = height
        this.eyecolor = eyecolor
        this.createdDate = createdDate
        this.placeOfRegistered = placeOfRegistered
        this.datecreatedserver = datecreatedserver
        this.uniqueuid = uniqueuid
        this.synstatus = synstatus
        this.datecreated = datecreated
        this.serverid = serverid
        this.macaddress = macaddress
        this.imei = imei
        this.agentname = agentname
        this.agentid = agentid
    }

    constructor() {}

    constructor(
        farmerid: String,
        picture: ByteArray,
        signature: ByteArray,
        height: String,
        eyecolor: String,
        createdDate: Date,
        placeOfRegistered: String,
        datecreated: Date
    ) {
        this.farmerid = farmerid
        this.picture = picture
        this.signature = signature
        this.height = height
        this.eyecolor = eyecolor
        this.createdDate = createdDate
        this.placeOfRegistered = placeOfRegistered
        this.datecreatedserver = datecreated
    }
}


