package com.uclgroupgh.form.entities.server

// Generated Jun 30, 2018 8:14:16 AM by Hibernate Tools 4.3.1


import java.util.Date

/**
 * Basicfarmerinfo generated by hbm2java
 */

class AggregatorInfo : java.io.Serializable {

    var id: Int? = null
    var othernames: String? = null
    var othername: String? = null
    var dateofbirth: Date? = null
    var placeofbirth: String? = null
    var gender: String? = null
    var hometown: String? = null
    var address: String? = null
    var tel: String? = null
    var levelofeducation: String? = null
    var religion: String? = null
    var maritalstatus: String? = null
    var community: String? = null
    var district: String? = null
    var region: String? = null
    var country: String? = null
    var datecreated: Date? = null
    var serverid: Int? = null
}


