package com.uclgroupgh.form.entities.server

// Generated Jun 30, 2018 8:14:16 AM by Hibernate Tools 4.3.1


import java.util.Date

/**
 * Basicfarmerinfo generated by hbm2java
 */

class Basicfarmerinfo : java.io.Serializable {

    var id: Int? = null
    var regagent: String? = null
    var uniqueuid: String? = null
    var farmerid: String? = null
    var surname: String? = null
    var othernames: String? = null
    var othername: String? = null
    var dateofbirth: Date? = null
    var placeofbirth: String? = null
    var gender: String? = null
    var hometown: String? = null
    var address: String? = null
    var tel: String? = null
    var levelofeducation: String? = null
    var religion: String? = null
    var maritalstatus: String? = null
    var community: String? = null
    var district: String? = null
    var region: String? = null
    var country: String? = null
    var datecreated: Date? = null
    var pending: Char? = null
    var agentid: String? = null
    var agentname: String? = null
    var imei: String? = null
    var macaddress: String? = null
    var email: String? = null
    var funding: String? = null
    var postbox: String? = null
    var serverid: Int? = null

    override fun toString(): String {
        return "Basicfarmerinfo{" +
                "id=" + id +
                ", regagent='" + regagent + '\''.toString() +
                ", uniqueuid='" + uniqueuid + '\''.toString() +
                ", farmerid='" + farmerid + '\''.toString() +
                ", surname='" + surname + '\''.toString() +
                ", othernames='" + othernames + '\''.toString() +
                ", dateofbirth=" + dateofbirth +
                ", placeofbirth='" + placeofbirth + '\''.toString() +
                ", gender='" + gender + '\''.toString() +
                ", hometown='" + hometown + '\''.toString() +
                ", address='" + address + '\''.toString() +
                ", tel='" + tel + '\''.toString() +
                ", levelofeducation='" + levelofeducation + '\''.toString() +
                ", religion='" + religion + '\''.toString() +
                ", maritalstatus='" + maritalstatus + '\''.toString() +
                ", community='" + community + '\''.toString() +
                ", district='" + district + '\''.toString() +
                ", region='" + region + '\''.toString() +
                ", country='" + country + '\''.toString() +
                ", datecreated=" + datecreated +
                ", pending=" + pending +
                ", agentid='" + agentid + '\''.toString() +
                ", agentname='" + agentname + '\''.toString() +
                ", imei='" + imei + '\''.toString() +
                ", macaddress='" + macaddress + '\''.toString() +
                ", email='" + email + '\''.toString() +
                ", funding='" + funding + '\''.toString() +
                ", postbox='" + postbox + '\''.toString() +
                '}'.toString()
    }
}


