package com.uclgroupgh.form.entities.server

// Generated Jun 30, 2018 8:14:16 AM by Hibernate Tools 4.3.1


import java.util.Date

/**
 * Farmerbiometrics generated by hbm2java
 */

class Farmerbiometrics : java.io.Serializable {


    var id: Int? = null
    var farmerid: String? = null
    var uniqueuid: String? = null
    var placeofregistered: String? = null
    var picture: ByteArray? = null
    var signature: ByteArray? = null
    var datecreated: Date? = null
    var picturename: String? = null
    var agentid: String? = null
    var agentname: String? = null
    var imei: String? = null
    var macaddress: String? = null
    var serverid: Int? = null
}


